In [3]:
import torch

defining Complex tensor

In [4]:
bra = torch.tensor([[1, 2.j], [-2, 1.j]])
bra

tensor([[ 1.+0.j,  0.+2.j],
        [-2.+0.j,  0.+1.j]])

Tensor Product

In [14]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

c = torch.tensordot(a, b, dims=0)
c

tensor([[[[ 5,  6],
          [ 7,  8]],

         [[10, 12],
          [14, 16]]],


        [[[15, 18],
          [21, 24]],

         [[20, 24],
          [28, 32]]]])

# Inner Product (Dirac Notation)

In [15]:
# Test
ket = torch.tensor([1, 2, 3.j]).reshape(-1, 1)
print(ket)

bra = torch.conj(ket).T
print(bra)

# inner product (Dirac notation)
inner_product = bra @ ket
print(inner_product)


tensor([[1.+0.j],
        [2.+0.j],
        [0.+3.j]])
tensor([[1.-0.j, 2.-0.j, 0.-3.j]])
tensor([[14.+0.j]])


In [58]:
def inner_product(bra, ket):
    return torch.conj(bra).T @ ket

In [16]:
def check_basis(vectors, normalize=False, verbose=True):
    """
    Check if the vectors are orthogonal and normalized (orthonormal basis)
    """ 
    # Check if all vectors are orthogonal (inner product is zero)
    orthogonal = all([inner_product(i, j) == 0 for i in vectors for j in vectors if i is not j])

    # Check if all vectors are normalized (inner product is one)
    normalized = all([inner_product(i, i) == 1 for i in vectors])

    # initial print
    if verbose:
        print(f'Vectors are orthogonal: {orthogonal} | Vectors are normalized: {normalized}')

    # if the vectors are not normalized, normalize them
    if not normalized and normalize and orthogonal:
        # normalize vectors (divide by the norm)
        vectors = [i / torch.sqrt(inner_product(i, i)) for i in vectors]
        if verbose:
            print('Vectors are orthogonal but not normalized. Normalizing...')
            print(f"vectors after normalization:")
            for i in vectors:
                print(i)

    return orthogonal and normalized


In [86]:
# Ex1: Computational basis (1 qubit)
vector1 = torch.tensor([0, 1]).reshape(-1, 1)
vector2 = torch.tensor([1, 0]).reshape(-1, 1)

check_basis([vector1, vector2], True);

Vectors are orthogonal: True | Vectors are normalized: True


In [87]:
# Ex2: Hadamard basis (1 qubit)
vector1 = torch.tensor([1, 1]).reshape(-1, 1)
vector2 = torch.tensor([1, -1]).reshape(-1, 1)

check_basis([vector1, vector2], True);

Vectors are orthogonal: True | Vectors are normalized: False
Vectors are orthogonal but not normalized. Normalizing...
vectors after normalization:
tensor([[0.7071],
        [0.7071]])
tensor([[ 0.7071],
        [-0.7071]])


In [90]:
# Ex3: 2 qubit basis
vector1 = torch.tensor([1, 0, 0, 0]).reshape(-1, 1)
vector2 = torch.tensor([0, 1, 0, 0]).reshape(-1, 1)
vector3 = torch.tensor([0, 0, 1, 0]).reshape(-1, 1)
vector4 = torch.tensor([0, 0, 0, 1]).reshape(-1, 1)

check_basis([vector1, vector2, vector3, vector4], True);

Vectors are orthogonal: True | Vectors are normalized: True
