In [4]:
import torch
from gates import *

In [5]:
# define 0, 1, +, - qubits
zero = torch.tensor([1, 0], dtype=torch.complex64)
one = torch.tensor([0, 1], dtype=torch.complex64)
plus = torch.tensor([1, 1], dtype=torch.complex64) / torch.sqrt(torch.tensor(2.0))
minus = torch.tensor([1, -1], dtype=torch.complex64) / torch.sqrt(torch.tensor(2.0))


In [6]:
print(CNOT(zero, zero))
print(CNOT(zero, one))
print(CNOT(one, zero))
print(CNOT(one, one))


tensor([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])
tensor([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j])
tensor([0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j])
tensor([0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j])


In [15]:
print(BellStateGate(zero, zero)) # should be 1/sqrt(2) * (|00> + |11>)
print(BellStateGate(zero, one))
print(BellStateGate(one, zero))
print(BellStateGate(one, one))

tensor([0.7071+0.j, 0.0000+0.j, 0.0000+0.j, 0.7071+0.j])
tensor([0.0000+0.j, 0.7071+0.j, 0.7071+0.j, 0.0000+0.j])
tensor([ 0.7071+0.j,  0.0000+0.j,  0.0000+0.j, -0.7071+0.j])
tensor([ 0.0000+0.j,  0.7071+0.j, -0.7071+0.j,  0.0000+0.j])
